### ISSUE TITLE
Issue in using training AnimateLCM SVD

### ISSUE THREAD

**Issue by habibian** [G-U-N/AnimateLCM#22]
Thanks for the great work, also for releasing the training script `train_svd_lcm.py`.

I am trying to reproduce the results using the provided `train_svd_lcm.py`, but after half of the training (20,000 / 50,000 itrs) don't see any improvement neither in loss value nor generation qualities (training on a single A100 on WebVid2M).

Could you please confirm if Ishould set the hyper-params as follows?

`accelerate launch train_svd_lcm.py \`
`    --pretrained_model_name_or_path=stabilityai/stable-video-diffusion-img2vid-xt \`
`    --per_gpu_batch_size=1 --gradient_accumulation_steps=1 \`
`    --max_train_steps=50000 \`
`    --width=576 \`
`    --height=320 \`
`    --checkpointing_steps=1000 --checkpoints_total_limit=1 \`
`    --learning_rate=1e-6 --lr_warmup_steps=1000 \`
`    --seed=123 \`
`    --adam_weight_decay=1e-3 \`
`    --mixed_precision="fp16" \`
`    --N=40 \`
`    --validation_steps=500 \`
`    --enable_xformers_memory_efficient_attention \`
`    --gradient_checkpointing \`
`    --output_dir="outputs" \`

In the current `train_svd_lcm.py`, the model is being trained on `576x320` resolutions, which is much lower than the standard SVD, i.e., `1024x572`. Would not this cause a problem as normal (non LCM) SVD suffer from generating lower resolution videos?

Any input is much appreciated :)

**Comment by G-U-N** [comment]
Hi, thanks for the interest! 

- I set the default resolution 576x 320 because  I find that even trained with lower resolution, it still works to accelerate the generation of SVD. The generation quality of SVD on resolution 576 x 320 is not ideal, and therefore even trained with lower resolutions,  you'd better log the generation results in the resolution of 1024x576.  Also, for better results, using 1024x576 for training is definitely a better choice when the resource is sufficient. 
- Also, I would recommend slightly decreasing the learning rate since you trained the model with only one GPU.

**Comment by G-U-N** [comment]
Also would say that the default hyper-parameters applied in the training script are not carefully tailored and should just be sub-optimal. For example, using `EMA` should generally increase the generation stability.

**Comment by habibian** [comment]
Thanks for the swift response :) 

I am now switching to 4xA100 and unfortunately still see vague blobs like the attachment. Curious to know at what iterations should I expect the generations start looking like a video? :)

Thanks!

![step_5000_val_img_7_2_1steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/be489674-0841-4d0d-8113-9a2d8d0856a3)

**Comment by G-U-N** [comment]
The results uploaded seem to be abnormal. It should not flash like this with unnatural colour. Here's what I obtained trained on 576x320. 

Training beginning, 0-iter, cfg = 1, inference step = 4
![step_1_val_img_7_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/60997859/b49d6e05-3641-4521-9fac-70cc7faf4fcc)




10k iter, cfg=1, inference step = 4
![step_14500_val_img_7_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/60997859/cf6d4137-9348-4859-8472-aee00e0ab001)

The devices are 8 A 800, and the batch size is set to 8 without gradient accumulation.

**Comment by G-U-N** [comment]
I just found the code at this [line](https://github.com/G-U-N/AnimateLCM/blob/master/animatelcm_svd/train_svd_lcm.py#L657) was a typo, and I fixed it. Just hope it did not mislead you.

**Comment by habibian** [comment]
Amazing! It start to look good after fixing the typo.

ThanQ :)

**Comment by G-U-N** [comment]
Awesome! Very glad to hear that : D.

**Comment by habibian** [comment]
Hey Fu-Yun,

After fixing the typo, I have been training the model on 8xA100s, which should be exactly like your setting then. Unfortunately, I still can't match your generations:

Training beginning, 0-iter, cfg = 1, inference step = 4
![step_1_val_img_7_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/91271d2a-ce80-4414-9bcc-4216ef167b37)

10k iter, cfg=1, inference step = 4
![step_10000_val_img_7_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/b09e3b86-aaf0-4d3f-ab93-06f86d602a1b)

20k iter, cfg=1, inference step = 4
![step_20000_val_img_7_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/0d0fc1e0-c7ea-4062-80b6-920152c0b208)

Any suggestion on why this is happening? 

I suspect it might be from the data. Currently I am training on WebVid2M-train (`results_2M_train.csv` with 2.5M videos) without any particular subsampling (based on resolution, content, etc.). Could you please elaborate a bit your training data?

Also, my dataloader does not do any particular transformation/augmentation except for normalizing pixel values to [-1, 1]. Would be great if you can share your WebVid dataloader if there is any particular detail missing.

Again, thanks a lot for your great contribution :)

**Comment by G-U-N** [comment]
Hey @habibian, just uploaded an example [dataset.py](https://github.com/G-U-N/AnimateLCM/blob/master/animatelcm_svd/dataset.py).

In addition to that, I would recommend freezing all the convolutional layers when training because convolution layers seem to be more vulnerable for fine-tuning. 

Hope this will help for better performance.

**Comment by habibian** [comment]
Thanks for the response @G-U-N .

Regarding the freezing the convolutional layers, do you mean the ones in ResBlocks? Is is part of your implementation, or I need to implement it?

Thanks!

**Comment by G-U-N** [comment]
Hi @habibian,

Yes, the ResBlocks. That was not implemented in the training script. But  it should be easy to achieve that through modifying [this line](https://github.com/G-U-N/AnimateLCM/blob/master/animatelcm_svd/train_svd_lcm.py#L809).

**Comment by habibian** [comment]
Hey @G-U-N ,

Thanks for the input. Following your suggestion, I kept `conv` layers in `resblocks` frozen during the training as:

```
    for name, para in unet.named_parameters():
        # freeze resnet convs as suggested in https://github.com/G-U-N/AnimateLCM/issues/22#issuecomment-2094802365
        if 'conv' in name and not ('conv_in' in name or 'conv_out' in name):
            para.requires_grad = False
        else:
            para.requires_grad = True
            parameters_list.append(para)
```

I actually observe some improvements in training with this modification as:

**Convs Frozen**: 20k iter, cfg=1, inference step = 4
![step_20000_val_img_7_1_4steps_frozen](https://github.com/G-U-N/AnimateLCM/assets/5611848/43e73469-bdbd-43bd-b090-9e565f6e935e)

**All Finetuned**: 20k iter, cfg=1, inference step = 4
![step_20000_val_img_7_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/71ec369b-31fa-4196-ae51-1b9edccff646)

However, I still see my trained models to have much lower quality compared to the SVD checkpoint that you guys have released [SVD checkpoint](https://huggingface.co/wangfuyun/AnimateLCM-SVD-xt): . Here are some more test examples to give  you some idea about how poor the quality of my replications are. So wonder if you have trained SVD checkpoint as I am doing here, or maybe there are some differences, i.e., in code, data, etc?

Thanks a lot for your guidance and support in replicating your excellent work :)


**Convs Frozen**: 20k iter, cfg=1, inference step = 4
![step_20000_val_img_4_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/c55f698b-31dd-4aca-b4bf-7c221335b97f)
![step_20000_val_img_3_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/46dae818-1659-40fb-b948-9c8bafb09b8e)
![step_20000_val_img_2_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/34206209-5fba-4e21-904c-39f4c0874aae)
![step_20000_val_img_1_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/86e76cb8-b9c9-4653-b023-f56d36726975)

**Comment by G-U-N** [comment]
Hey @habibian , I would say there's no too much difference. The only difference is that I tried to freeze more weights at the beginning of training instead of fully fine-tuing.  I didn't do too much ablation on that due to my limited GPU resources.

What about trying this:


```python
 for name, para in unet.named_parameters():
    if "transformer_block" in name and "temporal_transformer_block" not in name:
        para.requires_grad = True
        parameters_list.append(para)
```

Again, I would recommend logging the generated videos in resolution 1024 x 576. You will not get ideal results  on low resolutions even if you train the model successfully.



LMK if you get better results.

**Comment by G-U-N** [comment]
Hi @habibian, just checking in to see if you have any updates. Hope everything is going well on your end!

**Comment by habibian** [comment]
Hey @G-U-N 

Thanks for the suggestion and your great support here, much appreciated!

Following your last suggestion, instead of `finetuning all except resblocks` I am now only `finetuning spatial_transformer_blocks` that is actually improving the results as follows:

**Finetuning all except resblocks:** 20k iter, cfg=1, inference step = 4
![step_20000_val_img_2_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/4b852254-389b-4ae4-9a46-907a27fcd1fb)


**Finetuning spatial_transformer_blocks:** 20k iter, cfg=1, inference step = 4
![step_19000_val_img_2_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/628d6a56-ad5f-4b4a-8de0-fe0444cd5283)

**Finetuning all except resblocks:** 20k iter, cfg=1, inference step = 4
![step_20000_val_img_3_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/466ecfe2-6707-44d3-876f-1f9156213eee)

**Finetuning spatial_transformer_blocks:** 20k iter, cfg=1, inference step = 4
![step_19000_val_img_3_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/81c0d24a-5727-4c80-992d-3af6f2d6a5c4)

**Finetuning all except resblocks:** 20k iter, cfg=1, inference step = 4
![step_20000_val_img_4_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/c99d6c32-6add-4ce4-ad58-6cbc985ee1c1)

**Finetuning spatial_transformer_blocks:** 20k iter, cfg=1, inference step = 4
![step_19000_val_img_4_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/6298f950-222d-47ef-8b9d-61911cce6e64)

**Finetuning all except resblocks:** 20k iter, cfg=1, inference step = 4
![step_20000_val_img_7_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/b46ae089-a820-4696-96a8-0a27d7b2c06e)

**Finetuning spatial_transformer_blocks:** 20k iter, cfg=1, inference step = 4
![step_19000_val_img_7_1_4steps](https://github.com/G-U-N/AnimateLCM/assets/5611848/a4f812cd-12fe-4795-ab6b-9905c3d01e27)

And, here are the 1024 x 576 generated videos using my trained checkpoint (compared to your released checkpoint):

**Finetuning spatial_transformer_blocks:** 20k iter, cfg=1, inference step = 4
![000000](https://github.com/G-U-N/AnimateLCM/assets/5611848/f97c9296-fa4a-4658-a5c7-5a45d6e1564b)

**You released AnimateLCM-SVD-xt-1.1 checkpoint:** ? iter, cfg=1, inference step = 4
![000000](https://github.com/G-U-N/AnimateLCM/assets/5611848/d1b0a148-ebc2-4d3c-8427-999e00ec9035)

**Finetuning spatial_transformer_blocks:** 20k iter, cfg=1, inference step = 4
![000000](https://github.com/G-U-N/AnimateLCM/assets/5611848/4bc4b3b7-77c4-497d-b2a8-527c508bcfec)

**You released AnimateLCM-SVD-xt-1.1 checkpoint:** ? iter, cfg=1, inference step = 4
![000000](https://github.com/G-U-N/AnimateLCM/assets/5611848/03222722-42fc-41cd-92d9-7269542292c7)

As you see, there is still a gap in generation qualities, which I am not sure how can be reduced. Is the released checkpoint trained with 50K iterations? Any particular multi-stage training or lr scheduling involved?

Thanks :)

**Comment by G-U-N** [comment]
Hey @habibian. Very glad to see the improvement! And I really appreciate the detailed visual ablations.

I actually conducted the training in two-stage.

- 30k iterations with only spatial transformer block tuned with learning rate 1e-6. 
```
if "temporal_transformer_block" not in name and "transformer_block" in name
```
- 50k iterations with only temporal transformer block tuned with learning rate 3e-7. (The temporal weights of SVD is relatively large and vulnerable.) 
```
if "temporal_transformer_block" in name
```

Additionally, some more iterations on larger resolutions will help enhance the performance.

Hope this will make better performance!

**Comment by habibian** [comment]
Hey @G-U-N ,

Great, thanks for the elaboration. I will follow this multi stage training and get back to you about results. 

For that, could you please describe a bit the details of the large resolution training? More specifically:
- Training videos and resolution
- Number of iterations and learning rate

Thanks!

**Comment by G-U-N** [comment]
@habibian 

The details:

Training videos: bilinear interpolated webvid-2M. If you have other video dataset with larger resolution, that will be great.
Resolution: Only spatial transformer block, a 80 GB GPU should be able to train on resolution 1024x576. Only temporal transformer block, a 80 GB GPU should be able to train on resolution 768x448.
Iterations: 10k~30k
learning rate: 1e-6

**Comment by ersanliqiao** [comment]
05/11/2024 00:34:18 - INFO - __main__ -   Total optimization steps = 50000
Steps:   0%|                                                                                   | 0/50000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/vjuicefs_hz_cv_enhance_v1/public_data/11105507/video_edit/AnimateLCM/animatelcm_svd/train_svd_lcm.py", line 1337, in <module>
    main()
  File "/data/vjuicefs_hz_cv_enhance_v1/public_data/11105507/video_edit/AnimateLCM/animatelcm_svd/train_svd_lcm.py", line 1081, in main
    teacher_pred_cond = teacher_unet(inp_noisy_latents, timesteps, encoder_hidden_states, added_time_ids=added_time_ids).sample
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/diffusers/models/unet_spatio_temporal_condition.py", line 434, in forward
    sample, res_samples = downsample_block(
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/diffusers/models/unet_3d_blocks.py", line 2173, in forward
    hidden_states = attn(
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/diffusers/models/transformer_temporal.py", line 359, in forward
    hidden_states_mix = temporal_block(
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/diffusers/models/attention.py", line 509, in forward
    attn_output = self.attn1(norm_hidden_states, encoder_hidden_states=None)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 527, in forward
    return self.processor(
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 1175, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 321, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 341, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/xformers/ops/fmha/flash.py", line 458, in apply
    out, softmax_lse, rng_state = cls.OPERATOR(
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
  File "/root/miniconda3/envs/animatelcm_svd/lib/python3.9/site-packages/xformers/ops/fmha/flash.py", line 106, in _flash_fwd
    ) = _C_flashattention.fwd(
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by ersanliqiao** [comment]
> Hey @habibian. Very glad to see the improvement! And I really appreciate the detailed visual ablations.
> 
> I actually conducted the training in two-stage.
> 
> * 30k iterations with only spatial transformer block tuned with learning rate 1e-6.
> 
> ```
> if "temporal_transformer_block" not in name and "transformer_block" in name
> ```
> 
> * 50k iterations with only temporal transformer block tuned with learning rate 3e-7. (The temporal weights of SVD is relatively large and vulnerable.)
> 
> ```
> if "temporal_transformer_block" in name
> ```
> 
> Additionally, some more iterations on larger resolutions will help enhance the performance.
> 
> Hope this will make better performance!

Hi, I think in stage 2, it should  use unet weight saved from stage1 to initialize the unet weights of stage2, but target unet and teacher unet should be initialized from stalibity svd xt?  Am I right? But the code seemed not support this??

**Comment by G-U-N** [comment]
Hey @ersanliqiao.  

You should load the unet and target unet from your finetuned weight and initialize the teacher unet with stability weight. 

Try this at this [line](https://github.com/G-U-N/AnimateLCM/blob/master/animatelcm_svd/train_svd_lcm.py#L699)

```python
from safetensors.torch import load_file
finetuned_weight = load_file("xxx.safetensors","cpu")
unet.load_state_dict(finetuned_weight)
target_unet.load_state_dict(finetuned_weight)
del finetuned_weight
```

**Comment by ersanliqiao** [comment]
thank you!!

**Comment by dreamyou070** [comment]
hi @habibian 
can i ask you why you are trying to train the model?
I am trying to use AnimateLCM model, but do not check weather training is better or not yet.
Do you have any specific reason?

**Comment by habibian** [comment]
hi @dreamyou070 

I needed to retrain AnimateLCM on a different UNet to run faster than standard SVD architecture.

**Comment by haohang96** [comment]
Hi @G-U-N, thanks for your great open-source work

I have some questions about loss weighting when training svd-lcm ([codes](https://github.com/G-U-N/AnimateLCM/blob/fca744f916ad376b7590f2d853693ef19f3bd752/animatelcm_svd/train_svd_lcm.py#L1111C1-L1113C18)):
`loss = torch.mean(weights) * ...`,

where the **weights** is defined [here](https://github.com/G-U-N/AnimateLCM/blob/fca744f916ad376b7590f2d853693ef19f3bd752/animatelcm_svd/animate_lcm_utils.py#L48C9-L48C69):

`self.weights = (1/(self.sigmas[:-1] - self.sigmas[1:]))**0.1`

This formulation seems a bit different from the representation of λn in the arXiv paper:
$$\lambda_n = ((1 - \delta \frac{n}{N}))^{\gamma}$$

I'd like to know if the formulation used in the code is based on any reference paper or if it is just a heuristic setting.

**Comment by G-U-N** [comment]
Hey, @haohang96 . Yes, I would say the choice of weights is very heuristic and hard to give an explicit analysis. Most designs are  heuristic and should be sub-optimal.

**Comment by weleen** [comment]
@habibian Hi, have you obtained results similar to the released AnimateLCM-svd-xt? I fine-tuned the Spatial Transformer layer for 30k iterations, the results look like what you have shown above.

![leaf-7260246_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/58fb1c5f-db9f-4d9e-98d1-26c5be627684)
![grey-capped-flycatcher-8071233_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/f9a4144f-9351-45c5-8a90-e4ee3cb29f2e)
![bird-7586857_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/f20f2b5c-5eb7-4333-be11-fb7b56cfb9e7)
![halloween-4585684_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/e77dce8b-dac2-45ac-ba2c-0d7d10be3d98)
![squirrel-7985502_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/c756dd6f-8c69-4e55-970f-75a9e1b880cc)

![woman-4549327_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/213396e8-1bfe-42e9-b7fb-2103a8be70d0)

**Comment by weleen** [comment]
@habibian Hi, have you obtained results similar to the released AnimateLCM-svd-xt? I fine-tuned the Spatial Transformer layer for 30k iterations, the results appear as blurry as what you've shown above.

![bird-8014191_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/3d433a93-e9a5-46d8-b412-6878324783ce)
![halloween-4585684_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/9cc4c217-4cd0-4d77-8eb7-30a48d5cf8d3)
![leaf-7260246_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/db216f20-09fe-4408-9e45-8d23f79d94f3)
![squirrel-7985502_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/afa4afbb-1591-47ca-aa72-7d3bac4997a0)
![woman-4549327_1280-576-1024-4-1-1-False](https://github.com/user-attachments/assets/57c6fd26-36df-4ced-bc58-f609319e144b)

**Comment by weleen** [comment]
trainable parameters are set as follows:
```python

    unet.requires_grad_(False)
    parameters_list = []

    # Customize the parameters that need to be trained; if necessary, you can uncomment them yourself.

    for name, para in unet.named_parameters():
        # 1 stage: 30k iterations with only spatial transformer block tuned with learning rate 1e-6.
        #  Only temporal transformer block, a 80 GB GPU should be able to train on resolution 768x448.
        if args.training_stage == 1:
            if "temporal_transformer_blocks" not in name and "transformer_blocks" in name:
                para.requires_grad = True
                parameters_list.append(para)
        elif args.training_stage == 2:
        # 2 stage: 50k iterations with only temporal transformer block tuned with learning rate 3e-7. (The temporal weights of SVD is relatively large and vulnerable.)
        # Only spatial transformer block, a 80 GB GPU should be able to train on resolution 1024x576.
            if "temporal_transformer_blocks" in name:
                para.requires_grad = True
                parameters_list.append(para)
```
