### ISSUE TITLE
Header too large error when running app.py

### ISSUE THREAD

**Issue by dillfrescott** [G-U-N/AnimateLCM#27]
```python
Traceback (most recent call last):
  File "/home/cross/Downloads/animate/animatelcm_svd/app.py", line 59, in <module>
    model_select("AnimateLCM-SVD-xt-1.1.safetensors")
  File "/home/cross/Downloads/animate/animatelcm_svd/app.py", line 33, in model_select
    with safe_open(file_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by G-U-N** [comment]
This is probably because your safetensor file is broken. Redownloading it should fix the problem.
