### ISSUE TITLE
from multiprocessing.context import ForkProcess ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C:\Users\DELL\anaconda3\envs\animatelcm_svd\lib\multiprocessing\context.py)

### ISSUE THREAD

**Issue by nikhil8399** [G-U-N/AnimateLCM#28]
(animatelcm_svd) C:\Users\DELL\OneDrive\Desktop\ImagetoVideo\AnimateSVD model\AnimateLCM\animatelcm_svd>python app.py
Traceback (most recent call last):
  File "C:\Users\DELL\OneDrive\Desktop\ImagetoVideo\AnimateSVD model\AnimateLCM\animatelcm_svd\app.py", line 1, in <module>
    import spaces
  File "C:\Users\DELL\anaconda3\envs\animatelcm_svd\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "C:\Users\DELL\anaconda3\envs\animatelcm_svd\lib\site-packages\spaces\zero\decorator.py", line 21, in <module>
    from .wrappers import regular_function_wrapper
  File "C:\Users\DELL\anaconda3\envs\animatelcm_svd\lib\site-packages\spaces\zero\wrappers.py", line 15, in <module>
    from multiprocessing.context import ForkProcess
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C:\Users\DELL\anaconda3\envs\animatelcm_svd\lib\multiprocessing\context.py)

I got this error, how to solve it? please help

**Comment by G-U-N** [comment]
Oh, sorry. Just forgot to comment out the hugging face space wrapper. It should be fixed now.

**Comment by nikhil8399** [comment]
Now it is working.. Thank you
